package com.medicalapi.medical;
import java.util.ArrayList;
import java.util.List;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MedicalApplication {
	static ArrayList<MedicalSolutions> solutions = new ArrayList<MedicalSolutions>();
	public static void main(String[] args) {
		SpringApplication.run(MedicalApplication.class, args);
            solutions.add(new MedicalSolutions("Fever", "An elevated body temperature usually caused by an infection", "Rest, hydration, over-the-counter fever reducers such as acetaminophen or ibuprofen"));
            solutions.add(new MedicalSolutions("Cough", "A reflex action that clears the throat of mucus or foreign irritants", "Over-the-counter cough suppressants, hydration, avoiding triggers"));
            solutions.add(new MedicalSolutions("Sore Throat", "Pain, irritation or itchiness of the throat", "Gargling with warm saltwater, hydration, over-the-counter pain relievers, avoiding irritants"));
            solutions.add(new MedicalSolutions("Runny or Stuffy Nose", "Excess mucus in the nasal passages", "Over-the-counter decongestants, saline nasal spray, hydration, avoiding triggers"));
            solutions.add(new MedicalSolutions("Nausea", "An unpleasant sensation of wanting to vomit", "Avoiding solid foods, drinking clear liquids, ginger, over-the-counter anti-nausea medication"));
            solutions.add(new MedicalSolutions("Vomiting", "The forceful expulsion of the stomach contents through the mouth", "Rest, hydration, avoiding solid foods, drinking clear liquids, over-the-counter anti-nausea medication"));
            solutions.add(new MedicalSolutions("Diarrhea", "Frequent bowel movements with loose and watery stool", "Hydration, avoiding solid foods, drinking clear liquids, over-the-counter anti-diarrheal medication"));
            solutions.add(new MedicalSolutions("Constipation", "Difficulty passing stool, infrequent bowel movements", "Increasing fiber intake, hydration, over-the-counter stool softeners or laxatives"));
            solutions.add(new MedicalSolutions("Abdominal Pain", "Pain or discomfort in the abdominal area", "Rest, hydration, over-the-counter pain relievers, avoiding trigger foods or activities"));
            solutions.add(new MedicalSolutions("Back Pain", "Pain or discomfort in the back", "Rest, hot or cold compress, over-the-counter pain relievers, gentle exercise or stretches"));
            solutions.add(new MedicalSolutions("Joint Pain", "Pain or discomfort in the joints", "Rest, hot or cold compress, over-the-counter pain relievers, gentle exercise or stretches"));
            solutions.add(new MedicalSolutions("Muscle Pain", "Pain or discomfort in the muscles", "Rest, hot or cold compress, over-the-counter pain relievers, gentle exercise or stretches"));
            solutions.add(new MedicalSolutions("Fatigue", "Feeling of exhaustion or lack of energy", "Rest, hydration, healthy diet, exercise, avoiding overexertion"));
            solutions.add(new MedicalSolutions("Heartburn", "A burning sensation in the chest caused by stomach acid refluxing into the esophagus", "Avoiding trigger foods, eating smaller meals, avoiding lying down after eating, over-the-counter antacids"));
            solutions.add(new MedicalSolutions("Toothache", "Pain or discomfort in or around a tooth", "Rinsing with warm saltwater, over-the-counter pain relievers, avoiding hot or cold foods, seeking dental care if severe or persistent"));
            solutions.add(new MedicalSolutions("test", "test", "test"));
            solutions.add(new MedicalSolutions("Gastroenteritis", "Inflammation of the stomach and intestines, often causing diarrhea and vomiting", "Rest, hydration, avoiding solid foods, drinking clear liquids, over-the-counter anti-diarrheal medication (if appropriate), seeking medical attention if severe or persistent"));
            solutions.add(new MedicalSolutions("Yeast Infection", "An overgrowth of yeast that causes irritation and discomfort in the vaginal area", "Over-the-counter antifungal creams or suppositories, maintaining good hygiene, wearing breathable underwear, avoiding irritants"));
            solutions.add(new MedicalSolutions("Hemorrhoids", "Swollen blood vessels in the rectal area, often causing discomfort, itching, or bleeding", "Sitz baths, over-the-counter hemorrhoid creams or ointments, increasing fiber intake, staying hydrated"));
            solutions.add(new MedicalSolutions("Allergic Rhinitis", "Inflammation of the nasal passages due to an allergic reaction", "Avoiding allergens, over-the-counter antihistamines, nasal sprays, saline nasal irrigation"));
            solutions.add(new MedicalSolutions("Sinusitis", "Inflammation of the sinuses, often causing facial pain or pressure", "Nasal irrigation with saline solution, over-the-counter decongestants, pain relievers, warm compresses"));
            solutions.add(new MedicalSolutions("Acid Reflux", "A condition where stomach acid flows back into the esophagus", "Avoiding trigger foods, eating smaller meals, avoiding lying down after eating, over-the-counter antacids or acid reducers"));
            solutions.add(new MedicalSolutions("Heartburn", "A burning sensation in the chest caused by stomach acid refluxing into the esophagus", "Avoiding trigger foods, eating smaller meals, avoiding lying down after eating, over-the-counter antacids"));
            solutions.add(new MedicalSolutions("Indigestion", "Discomfort or pain in the upper abdomen, often associated with eating", "Eating smaller meals, avoiding trigger foods, over-the-counter antacids or acid reducers"));
            solutions.add(new MedicalSolutions("Motion Sickness", "Nausea, dizziness, or vomiting caused by motion", "Focusing on a fixed point, fresh air, over-the-counter motion sickness medication, avoiding reading or looking at screens"));
            solutions.add(new MedicalSolutions("Migraine", "A severe headache often accompanied by other symptoms like nausea and sensitivity to light or sound", "Rest in a quiet, dark room, over-the-counter pain relievers (if appropriate), prescription migraine medication (if prescribed), avoiding triggers"));
            solutions.add(new MedicalSolutions("Urinary Tract Infection (UTI)", "Infection in the urinary system, often causing frequent urination, pain or burning during urination", "Drinking plenty of water, over-the-counter urinary pain relievers, antibiotics (prescription medication), seeking medical attention"));
            solutions.add(new MedicalSolutions("High Blood Pressure", "Elevated blood pressure levels", "Adopting a healthy diet, regular exercise, reducing sodium intake, taking prescribed medication"));
            solutions.add(new MedicalSolutions("Asthma", "Chronic inflammation of the airways, leading to difficulty breathing", "Using inhalers as prescribed, avoiding triggers such as smoke or allergens, regular exercise"));
            solutions.add(new MedicalSolutions("Sprained Ankle", "Injury to the ligaments of the ankle, resulting in pain and swelling", "Resting the affected ankle, applying ice packs, elevating the foot, using compression bandages, taking over-the-counter pain relievers"));
            solutions.add(new MedicalSolutions("Sunburn", "Skin inflammation caused by excessive exposure to the sun's ultraviolet rays", "Applying aloe vera or moisturizing lotions, taking over-the-counter pain relievers, staying hydrated, avoiding further sun exposure"));
            solutions.add(new MedicalSolutions("Conjunctivitis", "Inflammation of the conjunctiva (the thin, transparent layer covering the white part of the eye and inner eyelids)", "Applying warm compresses to the eyes, practicing good hygiene, avoiding touching or rubbing the eyes, using prescribed eye drops"));
            solutions.add(new MedicalSolutions("Insect Bite/Sting", "Skin reaction resulting from an insect bite or sting, causing itching, swelling, or pain", "Cleaning the affected area, applying ice packs or cold compresses, using over-the-counter anti-itch creams or antihistamines, seeking medical attention if severe or allergic reaction occurs"));
            solutions.add(new MedicalSolutions("Common Cold", "Viral infection affecting the nose and throat, causing symptoms like runny nose, sore throat, and cough", "Rest, hydration, over-the-counter cold medications for symptom relief, practicing good hygiene to prevent spreading the virus"));
            solutions.add(new MedicalSolutions("Acne", "Skin condition characterized by pimples, blackheads, and whiteheads", "Regularly washing the face with a gentle cleanser, avoiding squeezing or picking at the pimples, using over-the-counter acne creams or gels, maintaining a healthy diet and lifestyle"));
            solutions.add(new MedicalSolutions("Anemia", "Condition characterized by a low red blood cell count, leading to fatigue and weakness", "Eating iron-rich foods, taking iron supplements as prescribed, consuming foods high in vitamin C to enhance iron absorption, seeking medical advice for underlying causes"));
            solutions.add(new MedicalSolutions("Gastritis", "Inflammation of the stomach lining, causing stomach pain, nausea, and indigestion", "Avoiding trigger foods and beverages (e.g., spicy or acidic), eating smaller, more frequent meals, taking over-the-counter antacids or acid reducers, seeking medical attention if symptoms persist or worsen"));
            solutions.add(new MedicalSolutions("Urinary Incontinence", "Involuntary leakage of urine", "Performing pelvic floor exercises (Kegels), maintaining a healthy weight, avoiding bladder irritants (e.g., caffeine, alcohol), using absorbent products, consulting a healthcare professional for further evaluation and treatment options"));
            solutions.add(new MedicalSolutions("Migraine", "Recurrent severe headaches often accompanied by other symptoms like nausea and sensitivity to light or sound", "Rest in a quiet, dark room, over-the-counter pain relievers (if appropriate), prescription migraine medication (if prescribed), avoiding triggers"));
            solutions.add(new MedicalSolutions("Otitis Media (Ear Infection)", "Infection or inflammation of the middle ear, leading to ear pain and possible hearing loss", "Using prescribed ear drops or antibiotics, applying warm compresses to the ear, taking over-the-counter pain relievers, avoiding exposure to cigarette smoke"));
            solutions.add(new MedicalSolutions("Ankle Sprain", "Injury to the ligaments of the ankle, resulting in pain, swelling, and limited mobility", "Resting the affected ankle, applying ice packs, using compression bandages or ankle braces, elevating the foot, practicing gentle exercises and stretches, seeking physical therapy if necessary"));
            solutions.add(new MedicalSolutions("Insomnia", "Difficulty falling asleep or staying asleep", "Establishing a consistent sleep schedule, creating a relaxing bedtime routine, ensuring a comfortable sleep environment, avoiding stimulating activities and electronic devices before bed, practicing relaxation techniques"));
            solutions.add(new MedicalSolutions("Gastroenteritis (Stomach Flu)", "Inflammation of the stomach and intestines, causing symptoms like diarrhea, vomiting, and abdominal pain", "Rest, hydration, consuming bland foods, avoiding solid foods initially, gradually reintroducing easy-to-digest foods, taking over-the-counter anti-diarrheal medications (if appropriate), seeking medical attention if symptoms persist or worsen"));
            solutions.add(new MedicalSolutions("Sciatica", "Pain that radiates along the sciatic nerve, typically felt in the lower back, buttocks, and down one leg", "Applying hot or cold packs to the affected area, taking over-the-counter pain relievers, gentle stretching exercises, maintaining good posture, seeking physical therapy for targeted exercises and treatments"));
            solutions.add(new MedicalSolutions("Anemia", "Condition characterized by a low red blood cell count, leading to fatigue, weakness, and shortness of breath", "Eating a balanced diet rich in iron, vitamin B12, and folate, taking prescribed iron or vitamin supplements, consuming foods that enhance iron absorption (e.g., vitamin C-rich foods), seeking medical advice for underlying causes and potential treatments"));
            solutions.add(new MedicalSolutions("Gingivitis", "Inflammation and infection of the gums, causing redness, swelling, and tenderness", "Practicing good oral hygiene (regular brushing, flossing, and rinsing with mouthwash), scheduling regular dental cleanings, avoiding tobacco products, using antimicrobial mouthwash, seeking dental care for proper evaluation and treatment"));
            solutions.add(new MedicalSolutions("Sinus Infection (Sinusitis)", "Inflammation of the sinuses, often caused by a viral or bacterial infection, resulting in facial pain, congestion, and nasal discharge", "Using saline nasal irrigation, taking over-the-counter decongestants or nasal sprays (if appropriate), applying warm compresses to the affected sinuses, staying hydrated, seeking medical attention if symptoms persist or worsen"));
        }

}
